# permissions for end users to view bookstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookstore-viewer-role
rules:
- apiGroups:
  - core.gopher.com
  resources:
  - bookstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.gopher.com
  resources:
  - bookstores/status
  verbs:
  - get
